name: Sample job
on: workflow_dispatch
jobs:
 first-job:
    runs-on: ubuntu-latest
    steps:
    - name: print greeting
      run: echo "this is a build"
    - name: sample steps
      run: echo "this is a job"
    - name: sample
      run: |
        echo "this is a job"
        echo "this is a sample"
       
